config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'top#index', as: :top
  get 'tweet', to: 'tweet#new', as: :tweet_new
  post 'tweet/create', to: 'tweet#create', as: :tweet
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets

  validates :provider, presence: true
  validates :uid, presence: true
  validates :image_url, presence: true
  validates :token, presence: true
  validates :secret, presence: true

  def self.find_or_create_from_auth_hash(auth_hash)

    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    image_url = auth_hash[:info][:image]
    token = auth_hash[:credentials][:token]
    secret = auth_hash[:credentials][:secret]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.image_url = image_url
      user.token = token
      user.secret = secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def require_login
    return if logged_in?
    redirect_to root_url, notice: 'ログインしてください'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_or_create_from_auth_hash(auth)

    if user
      session[:user_id] = user.id
      redirect_to tweet_new_url, notice: 'ログインしました'
    else
      redirect_to root_url, alert: 'ログインに失敗しました'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  before_action :require_login

  def new
  end

  def create
    @tweet = Tweet.new

    begin
      tweet = twitter_client(current_user.id).update(params[:text])

      @tweet.user = current_user
      @tweet.tweet_id = tweet.id
      minute = params[:num].to_i
      @tweet.destroy_date = DateTime.now + Rational(minute, 24 * 60)
      @tweet.save
      redirect_to tweet_new_url, notice: 'つぶやきました！'
    rescue => error
      STDERR.puts error
      redirect_to tweet_new_url, notice: error
    end
  end

  def can_tweet_destroy
    tweets = Tweet.where("destroy_date <= now()")
    tweets.each do |tweet|
      begin
        twitter_client(tweet.user.id).destroy_status(tweet.tweet_id)
        puts "succese!"
      rescue => error
        STDERR.puts error
      ensure
        Tweet.delete(tweet)
      end
    end
  end

  def twitter_client(user_id)
    Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
      user = User.find(user_id)
      config.access_token = user.token
      config.access_token_secret = user.secret
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_list
    [
      ['３分', 3],
      ['５分', 5],
      ['１０分', 10],
      ['３０分', 30],
      ['１時間', 60],
      ['３時間', 180],
      ['６時間', 360],
      ['１２時間', 720],
      ['１日', 1440]
    ]
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Temp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('pen.png') %>
    <meta name="twitter:card" content='summary' />
    <meta property="og:url" content='http://temptweet.site/' />
    <meta property="og:title" content='Temp -ツイートを一定時間で削除！-' />
    <meta property="og:description" content='ツイートを指定した時間に削除するWebアプリです。' />
    <meta property="og:image" content="#{image_url('pen.png')}" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="ui borderless main menu">
      <div class="ui text container">
        <% if current_user %>
          <%= link_to tweet_new_url, class: "header item" do %>
            Temp
          <% end %>
          <div class="right menu">
            <div class="ui simple dropdown item">
              <%= image_tag current_user.image_url, class: 'menu-user-icon' %>
              <i class="dropdown icon"></i>
              <div class="menu">
                <%= link_to logout_path, class: "item" do %>
                  ログアウト
                <% end %>
              </div>
            </div>
          </div>
          <% else %>
            <%= link_to root_url, class: "header item" do %>
              Temp
            <% end %>
            <div class="right menu">
              <%= link_to '/auth/twitter', class: "item" do %>
                ログイン
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
    <% if notice %>
      <div class="ui text container">
        <div class="ui mini green message">
          <i class="close icon"></i>
          <%= notice %>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <div class="ui text container">
        <div class="ui mini red message">
          <i class="close icon"></i>
          <%= alert %>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <div class="center">
      <div class="ui horizontal small divided link list">
        <%= link_to root_url, class: "item" do %>
          © 2018 Temp
        <% end %>
      </div>
    </div>
  </body>
  <script>
  $('.message .close')
    .on('click', function() {
      $(this)
        .closest('.message')
        .transition('fade')
      ;
    })
  ;</script>
</html>

app/views/top/index.html.slim
.ui.raised.very.padded.text.container.segment
  div.twitter
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  p.catch ツイートを決まった時間に自動で消すことができるアプリです

  - if current_user
    .center
      = link_to tweet_new_url, class: 'ui button' do
        i.share.icon
        span Tweet画面にいく
  - else
    = link_to 'Twitterでログインする', '/auth/twitter', class: "positive ui fluid submit button"
    p.twitter-notice ※当サービスは自動でツイートすることはありません。
  br
  p.caution.center ※テスト版のため突然サイトを停止させることがあります。

app/views/tweet/new.html.slim
.ui.raised.very.padded.text.container.segment
  .ui.form
    = form_tag tweet_url do
      .field
        = text_area_tag :text, '', maxlength: 280, placeholder: 'ツイートを入力'
      .field
        = select_tag :num, options_for_select(time_list), class: 'ui fluid dropdown'
      .center
        = submit_tag 'ツイートする', class: 'ui teal submit button'